### 테스트
GET http://localhost:8000/

### 테스트
POST http://localhost:3000/predict
Content-Type: application/json

{
  "instances": [
    [
      1.0,   
      2.0,  
      3.0,  
      4.0,  
      50.0, 
      1.5,  
      0.1,  
      0.2,   
      0.3,   
      0.4,  
      1,    
      0,   
      10.0,  
      20.0,
      30.0,  
      40.0, 
      100.0,
      200.0, 
      300.0,
      400.0, 
      1,    
      10,  
      20   
    ]
  ]
}
